version: '3.8'

services:
  postgresDB:
    image: postgres:latest
    env_file: ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: ${DB_HOST}
    ports: 
      - "5432:5432"

  app:
    build: .
    ports: 
      - "3001:3001"
    depends_on: 
      - postgresDB
    env_file: ./.env
    environment:
      PORT: ${PORT}
      DB_URI: ${DB_URI}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
